export const commodities = [
    "Apple",
    "Apricot(Jardalu/Khumani)",
    "Bajra(Pearl Millet/Cumbu)",
    "Banana",
    "Bengal Gram(Gram)(Whole)",
    "Ber(Zizyphus/Borehannu)",
    "Black Gram Dal (Urd Dal)",
    "Black Pepper",
    "Bottle gourd",
    "Cardamoms",
    "Chakotha",
    "Cherry",
    "Chikoos(Sapota)",
    "Cocoa",
    "Coconut",
    "Coffee",
    "Cotton",
    "Cowpea (Lobia/Karamani)",
    "Custard Apple (Sharifa)",
    "Fig(Anjura/Anjeer)",
    "Foxtail Millet(Navane)",
    "Ginger(Green)",
    "Grapes",
    "Green Gram (Moong)(Whole)",
    "Groundnut",
    "Guava",
    "Jack Fruit",
    "Jowar",
    "Jute",
    "Kabuli Channa(Chickpeas-White)",
    "Karbuja(Musk Melon)",
    "Kinnow",
    "Lemon",
    "Lentil (Masur)(Whole)",
    "Maize",
    "Mango",
    "Moath Dal",
    "Orange",
    "Papaya",
    "Pear(Marasebu)",
    "Pegeon Pea (Arhar Fali)",
    "Pineapple",
    "Plum",
    "Pomegranate",
    "Pumpkin",
    "Rice",
    "Sesamum(Sesame,Gingelly,Til)",
    "Soyabean",
    "Sugarcane",
    "Tomato",
    "Turmeric",
    "Water Melon",
  ];